openapi: 3.1.0
info:
    title: Statistics service API
    version: 1.0.0

paths:
    /v1/temp:
        get:
            summary: Temp handler
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
