@startuml C4 Context Diagram

!include <C4/C4_Context>

title Диаграмма контекста социальной сети

' Пользователи и системы
Person(user, 'Пользователь')

System(social_network, 'Социальная сеть')


' Связи
Rel(user, social_network, 'Регистририруется; создаёт, обновляет и удаляет посты; получает стены с постами пользователей; ставит лайки и смотрит статистику по постам (лайки, просмотры), оставляет комментарии к постам и просматривает их')

@enduml